# /etc/unbound/unbound.conf

server:
    interface: 0.0.0.0
    interface: ::0
    access-control: 192.168.30.0/24 allow
    access-control: 192.168.20.0/24 allow
    access-control: 127.0.0.0/8 allow
    chroot: ""
    verbosity: 1
    hide-identity: yes
    hide-version: yes
    do-daemonize: yes
    username: "unbound"
    directory: "/etc/unbound"
    logfile: "/var/log/unbound/unbound.log"
    use-syslog: no
    pidfile: "/var/run/unbound/unbound.pid"
    local-data: "mail.lab.local. IN A 192.168.20.3"
    local-data: "lab.local. IN MX 10 mail.lab.local"
forward-zone:
    name: "."
    forward-addr: 1.1.1.1@53
    forward-addr: 8.8.8.8@53
